vars

diff --git a/.github/workflows/daily-automatic-update.yml b/.github/workflows/daily-automatic-update.yml
--- a/.github/workflows/daily-automatic-update.yml
+++ b/.github/workflows/daily-automatic-update.yml
@@ -5,11 +5,11 @@ on:
   workflow_dispatch:
 
 env:
-  Username: ${{ secrets.USERNAME }}
-  Token: ${{ secrets.TOKEN }}
-  Name: ${{ secrets.NAME }}
-  Email: ${{ secrets.EMAIL }}
-  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
+  USERNAME: ${{ secrets.USERNAME }}
+  TOKEN: ${{ secrets.TOKEN }}
+  NAME: ${{ secrets.NAME }}
+  EMAIL: ${{ secrets.EMAIL }}
+  NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
 
 jobs:
 
@@ -29,8 +29,26 @@ jobs:
         with:
           dotnet-version: 9.0.x
 
-      - name: Install dependencies
-        run: dotnet restore
+      - name: Install dependencies with retry
+        run: |
+          retries=5
+          base_wait_time=15
+          exponent=2
+
+          for i in $(seq 1 $retries); do
+            if dotnet restore; then
+              break
+            fi
+
+            if [ $i -lt $retries ]; then
+              wait_time=$(awk "BEGIN {print int($base_wait_time * ($exponent ^ ($i - 1)))}")
+              echo "dotnet restore failed, retrying in $wait_time seconds..."
+              sleep $wait_time
+            else
+              echo "dotnet restore failed after $retries retries."
+              exit 1
+            fi
+          done
 
       - name: Build
         run: dotnet build --configuration Release --no-restore
